alpa = input()
S = alpa.lower()

a = S.find('a')
b = S.find('b')
c = S.find('c')
d = S.find('d')
e = S.find('e')
f = S.find('f')
g = S.find('g')
h = S.find('h')
i = S.find('i')
j = S.find('j')
k = S.find('k')
l = S.find('l')
m = S.find('m')
n = S.find('n')
o = S.find('o')
p = S.find('p')
q = S.find('q')
r = S.find('r')
s = S.find('s')
t = S.find('t')
u = S.find('u')
v = S.find('v')
w = S.find('w')
x = S.find('x')
y = S.find('y')
z = S.find('z')

    
if len(S) <= 100:
    print(a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z)
